version: "3.5"

services:
  database:
    container_name: ${PROJECT_NAME}_database
    image: kartoza/postgis:${POSTGRES_MAJOR_VERSION}-${POSTGIS_MAJOR_VERSION}.${POSTGIS_MINOR_RELEASE}
    env_file:
      - .env
    volumes:
      - database_volume:/var/lib/postgresql
    environment:
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology,postgis_raster
      - RUN_AS_ROOT=true
    ports:
      - "25432:5432"
    restart: on-failure

  rabbitmq:
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    env_file:
      - .env
    networks:
      - service
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    ports:
      - "8002:5672"
      - "8003:15672"

volumes:
  rabbitmq_volume: {}
  database_volume: {}

networks:
  service:
    name: service
